apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  type: LoadBalancer  # Use "NodePort" for local clusters or "LoadBalancer" for cloud providers
  ports:
  - protocol: TCP
    port: 80         # External port
    targetPort: 8080 # Internal container port
