name: Simple CI

# Trigger the workflow on pushes to the simple_go_app branch and on pull requests
on:
  push:
    branches:
      - simple_go_app
  pull_request:
    branches:
      - simple_go_app

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'  # Specify the Go version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod download

      # Step 4: Run tests
      - name: Run tests
        run: go test ./...
